# Generated by Django 6.0.1 on 2026-01-11 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderstatushistory",
            name="new_status",
            field=models.IntegerField(
                choices=[
                    (0, "Pending"),
                    (10, "Confirmed"),
                    (20, "Processing"),
                    (30, "Shipped"),
                    (40, "Delivered"),
                    (50, "Cancelled"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="orderstatushistory",
            name="old_status",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (0, "Pending"),
                    (10, "Confirmed"),
                    (20, "Processing"),
                    (30, "Shipped"),
                    (40, "Delivered"),
                    (50, "Cancelled"),
                ],
                null=True,
            ),
        ),
    ]
