# Generated by Django 6.0.1 on 2026-01-11 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_orderstatushistory_new_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderstatushistory",
            name="change_source",
            field=models.CharField(
                choices=[("api", "API"), ("admin", "Admin"), ("system", "System")],
                db_index=True,
                default="system",
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.CheckConstraint(
                condition=models.Q(("stock_quantity__gte", 0)),
                name="stock_quantity_gte_0",
            ),
        ),
    ]
